name: database
version: 1.0.0

publish_to: none

environment:
  sdk: '>=3.10.0 <4.0.0'

resolution: workspace

dependencies:
  database_account_foreground:
    path: "../database_account_foreground"
  database_common:
    path: "../database_common"
  database_model:
    path: "../database_model"
