name: native_utils
description: "FFI code"
version: 0.0.1

publish_to: 'none'

environment:
  sdk: '>=3.10.0 <4.0.0'

resolution: workspace

dependencies:
  native_utils_ffi:
    path: "../native_utils_ffi"
  native_utils_web:
    path: "../native_utils_web"
  native_utils_common:
    path: "../native_utils_common"
