name: database_provider_web
description: "Database provider web implementation"
version: 0.0.1

publish_to: 'none'

environment:
  sdk: '>=3.10.0 <4.0.0'

resolution: workspace

dependencies:
  logging: ^1.2.0
  drift: ^2.26.0
  web: ^1.1.1

  database_utils:
    path: "../database_utils"
  encryption_common:
    path: "../encryption_common"

  utils:
    path: "../utils"
