name: database_provider_native
description: "Database provider native implementation"
version: 0.0.1

publish_to: 'none'

environment:
  sdk: '>=3.10.0 <4.0.0'
  flutter: '>=3.35.0'

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  logging: ^1.2.0
  path_provider: ^2.1.1
  path: ^1.9.0

  drift: ^2.26.0
  sqlcipher_flutter_libs: ^0.6.5
  sqlite3: ^2.7.5

  database_utils:
    path: "../database_utils"

  encryption:
    path: "../encryption"
