name: database_model
version: 1.0.0

publish_to: none

environment:
  sdk: '>=3.10.0 <4.0.0'

resolution: workspace

dependencies:
  archive: ^4.0.7
  openapi:
    path: "../api_client"

  utils:
    path: "../utils"

dev_dependencies:
  test: ^1.26.0
