name: encryption_native
description: "Encryption related utils implementation for native platforms"
version: 0.0.1

publish_to: 'none'

environment:
  sdk: '>=3.10.0 <4.0.0'
  flutter: '>=3.35.0'

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  logging: ^1.2.0
  flutter_secure_storage: ^9.2.4

  native_utils:
    path: "../native_utils"

  utils:
    path: "../utils"

  encryption_common:
    path: "../encryption_common"
