name: database_converter
version: 1.0.0

publish_to: none

environment:
  sdk: '>=3.10.0 <4.0.0'

resolution: workspace

dependencies:
  drift: ^2.30.1

  openapi:
    path: "../api_client"

  database_model:
    path: "../database_model"

  utils:
    path: "../utils"
