name: database_account
version: 1.0.0

publish_to: none

environment:
  sdk: '>=3.10.0 <4.0.0'

resolution: workspace

dependencies:
  async: ^2.11.0
  rxdart: ^0.28.0
  collection: ^1.18.0
  drift: ^2.30.1
  uuid: ^4.4.2

  openapi:
    path: "../api_client"

  database_model:
    path: "../database_model"
  database_converter:
    path: "../database_converter"
  database_utils:
    path: "../database_utils"

  utils:
    path: "../utils"

dev_dependencies:
  build_runner: ^2.4.8
  drift_dev: ^2.30.1
  test: ^1.26.0
